export { default as tsconfigPaths } from 'vite-tsconfig-paths'
export type { PluginOptions } from 'vite-tsconfig-paths'
export type { Plugin, UserWorkspaceConfig, ViteUserConfig } from 'vitest/config'
export { vitestConfigDefaults, vitestProjectDefaults } from './defaults.js'
export { plugins } from './plugins.js'
export { vitestConfig, vitestProject } from './shareableConfigs.js'
export { createVitestConfig, createVitestProject } from './utils.js'
