import type { Linter } from 'eslint'
import globalIdentifiers from 'globals'

const { browser, node, nodeBuiltin, vitest } = globalIdentifiers

/**
 * An object representing the
 * {@link https://vitest.dev/config/#globals | globals} provided by
 * {@link https://vitest.dev | **Vitest**} for use in testing.
 *
 * @since 0.0.1
 * @public
 */
export const vitestGlobals = {
  suite: 'writable',
  test: 'writable',
  chai: 'writable',
  describe: 'writable',
  it: 'writable',
  expectTypeOf: 'writable',
  assertType: 'writable',
  expect: 'writable',
  assert: 'writable',
  vitest: 'writable',
  vi: 'writable',
  beforeAll: 'writable',
  afterAll: 'writable',
  beforeEach: 'writable',
  afterEach: 'writable',
  onTestFailed: 'writable',
  onTestFinished: 'writable',
} as const satisfies Linter.Globals satisfies {
  readonly suite: 'writable'
  readonly test: 'writable'
  readonly chai: 'writable'
  readonly describe: 'writable'
  readonly it: 'writable'
  readonly expectTypeOf: 'writable'
  readonly assertType: 'writable'
  readonly expect: 'writable'
  readonly assert: 'writable'
  readonly vitest: 'writable'
  readonly vi: 'writable'
  readonly beforeAll: 'writable'
  readonly afterAll: 'writable'
  readonly beforeEach: 'writable'
  readonly afterEach: 'writable'
  readonly onTestFailed: 'writable'
  readonly onTestFinished: 'writable'
} as {
  readonly suite: 'writable'
  readonly test: 'writable'
  readonly chai: 'writable'
  readonly describe: 'writable'
  readonly it: 'writable'
  readonly expectTypeOf: 'writable'
  readonly assertType: 'writable'
  readonly expect: 'writable'
  readonly assert: 'writable'
  readonly vitest: 'writable'
  readonly vi: 'writable'
  readonly beforeAll: 'writable'
  readonly afterAll: 'writable'
  readonly beforeEach: 'writable'
  readonly afterEach: 'writable'
  readonly onTestFailed: 'writable'
  readonly onTestFinished: 'writable'
}

/**
 * An object that specifies which global
 * variables are available during linting.
 *
 * @since 0.0.1
 * @public
 */
export const globals =
  /* @__PURE__ */
  Object.assign(
    {
      ...browser,
      ...node,
      ...nodeBuiltin,
    } as const satisfies Linter.Globals,

    {
      ...vitest,
      ...vitestGlobals,
    } as const satisfies Linter.Globals,
  ) satisfies Linter.Globals satisfies {
    readonly AbortController: false
    readonly AbortSignal: false
    readonly AsyncDisposableStack: false
    readonly atob: false
    readonly Blob: false
    readonly BroadcastChannel: false
    readonly btoa: false
    readonly Buffer: false
    readonly ByteLengthQueuingStrategy: false
    readonly clearImmediate: false
    readonly clearInterval: false
    readonly clearTimeout: false
    readonly CloseEvent: false
    readonly CompressionStream: false
    readonly console: false
    readonly CountQueuingStrategy: false
    readonly crypto: false
    readonly Crypto: false
    readonly CryptoKey: false
    readonly CustomEvent: false
    readonly DecompressionStream: false
    readonly DisposableStack: false
    readonly DOMException: false
    readonly Event: false
    readonly EventTarget: false
    readonly fetch: false
    readonly File: false
    readonly FormData: false
    readonly global: false
    readonly Headers: false
    readonly MessageChannel: false
    readonly MessageEvent: false
    readonly MessagePort: false
    readonly navigator: false
    readonly Navigator: false
    readonly performance: false
    readonly Performance: false
    readonly PerformanceEntry: false
    readonly PerformanceMark: false
    readonly PerformanceMeasure: false
    readonly PerformanceObserver: false
    readonly PerformanceObserverEntryList: false
    readonly PerformanceResourceTiming: false
    readonly process: false
    readonly queueMicrotask: false
    readonly ReadableByteStreamController: false
    readonly ReadableStream: false
    readonly ReadableStreamBYOBReader: false
    readonly ReadableStreamBYOBRequest: false
    readonly ReadableStreamDefaultController: false
    readonly ReadableStreamDefaultReader: false
    readonly Request: false
    readonly Response: false
    readonly setImmediate: false
    readonly setInterval: false
    readonly setTimeout: false
    readonly structuredClone: false
    readonly SubtleCrypto: false
    readonly SuppressedError: false
    readonly TextDecoder: false
    readonly TextDecoderStream: false
    readonly TextEncoder: false
    readonly TextEncoderStream: false
    readonly TransformStream: false
    readonly TransformStreamDefaultController: false
    readonly URL: false
    readonly URLPattern: false
    readonly URLSearchParams: false
    readonly WebAssembly: false
    readonly WebSocket: false
    readonly WritableStream: false
    readonly WritableStreamDefaultController: false
    readonly WritableStreamDefaultWriter: false
    readonly __dirname: false
    readonly __filename: false
    readonly exports: true
    readonly module: false
    readonly require: false
    readonly AbsoluteOrientationSensor: false
    readonly AbstractRange: false
    readonly Accelerometer: false
    readonly addEventListener: false
    readonly ai: false
    readonly AI: false
    readonly AICreateMonitor: false
    readonly AITextSession: false
    readonly alert: false
    readonly AnalyserNode: false
    readonly Animation: false
    readonly AnimationEffect: false
    readonly AnimationEvent: false
    readonly AnimationPlaybackEvent: false
    readonly AnimationTimeline: false
    readonly Attr: false
    readonly Audio: false
    readonly AudioBuffer: false
    readonly AudioBufferSourceNode: false
    readonly AudioContext: false
    readonly AudioData: false
    readonly AudioDecoder: false
    readonly AudioDestinationNode: false
    readonly AudioEncoder: false
    readonly AudioListener: false
    readonly AudioNode: false
    readonly AudioParam: false
    readonly AudioParamMap: false
    readonly AudioProcessingEvent: false
    readonly AudioScheduledSourceNode: false
    readonly AudioSinkInfo: false
    readonly AudioWorklet: false
    readonly AudioWorkletGlobalScope: false
    readonly AudioWorkletNode: false
    readonly AudioWorkletProcessor: false
    readonly AuthenticatorAssertionResponse: false
    readonly AuthenticatorAttestationResponse: false
    readonly AuthenticatorResponse: false
    readonly BackgroundFetchManager: false
    readonly BackgroundFetchRecord: false
    readonly BackgroundFetchRegistration: false
    readonly BarcodeDetector: false
    readonly BarProp: false
    readonly BaseAudioContext: false
    readonly BatteryManager: false
    readonly BeforeUnloadEvent: false
    readonly BiquadFilterNode: false
    readonly BlobEvent: false
    readonly Bluetooth: false
    readonly BluetoothCharacteristicProperties: false
    readonly BluetoothDevice: false
    readonly BluetoothRemoteGATTCharacteristic: false
    readonly BluetoothRemoteGATTDescriptor: false
    readonly BluetoothRemoteGATTServer: false
    readonly BluetoothRemoteGATTService: false
    readonly BluetoothUUID: false
    readonly blur: false
    readonly BrowserCaptureMediaStreamTrack: false
    readonly Cache: false
    readonly caches: false
    readonly CacheStorage: false
    readonly cancelAnimationFrame: false
    readonly cancelIdleCallback: false
    readonly CanvasCaptureMediaStream: false
    readonly CanvasCaptureMediaStreamTrack: false
    readonly CanvasGradient: false
    readonly CanvasPattern: false
    readonly CanvasRenderingContext2D: false
    readonly CaptureController: false
    readonly CaretPosition: false
    readonly CDATASection: false
    readonly ChannelMergerNode: false
    readonly ChannelSplitterNode: false
    readonly ChapterInformation: false
    readonly CharacterBoundsUpdateEvent: false
    readonly CharacterData: false
    readonly clientInformation: false
    readonly Clipboard: false
    readonly ClipboardEvent: false
    readonly ClipboardItem: false
    readonly close: false
    readonly closed: false
    readonly CloseWatcher: false
    readonly CommandEvent: false
    readonly Comment: false
    readonly CompositionEvent: false
    readonly confirm: false
    readonly ConstantSourceNode: false
    readonly ContentVisibilityAutoStateChangeEvent: false
    readonly ConvolverNode: false
    readonly CookieChangeEvent: false
    readonly CookieDeprecationLabel: false
    readonly cookieStore: false
    readonly CookieStore: false
    readonly CookieStoreManager: false
    readonly createImageBitmap: false
    readonly Credential: false
    readonly credentialless: false
    readonly CredentialsContainer: false
    readonly CropTarget: false
    readonly crossOriginIsolated: false
    readonly CSPViolationReportBody: false
    readonly CSS: false
    readonly CSSAnimation: false
    readonly CSSConditionRule: false
    readonly CSSContainerRule: false
    readonly CSSCounterStyleRule: false
    readonly CSSFontFaceRule: false
    readonly CSSFontFeatureValuesRule: false
    readonly CSSFontPaletteValuesRule: false
    readonly CSSGroupingRule: false
    readonly CSSImageValue: false
    readonly CSSImportRule: false
    readonly CSSKeyframeRule: false
    readonly CSSKeyframesRule: false
    readonly CSSKeywordValue: false
    readonly CSSLayerBlockRule: false
    readonly CSSLayerStatementRule: false
    readonly CSSMarginRule: false
    readonly CSSMathClamp: false
    readonly CSSMathInvert: false
    readonly CSSMathMax: false
    readonly CSSMathMin: false
    readonly CSSMathNegate: false
    readonly CSSMathProduct: false
    readonly CSSMathSum: false
    readonly CSSMathValue: false
    readonly CSSMatrixComponent: false
    readonly CSSMediaRule: false
    readonly CSSNamespaceRule: false
    readonly CSSNestedDeclarations: false
    readonly CSSNumericArray: false
    readonly CSSNumericValue: false
    readonly CSSPageDescriptors: false
    readonly CSSPageRule: false
    readonly CSSPerspective: false
    readonly CSSPositionTryDescriptors: false
    readonly CSSPositionTryRule: false
    readonly CSSPositionValue: false
    readonly CSSPropertyRule: false
    readonly CSSRotate: false
    readonly CSSRule: false
    readonly CSSRuleList: false
    readonly CSSScale: false
    readonly CSSScopeRule: false
    readonly CSSSkew: false
    readonly CSSSkewX: false
    readonly CSSSkewY: false
    readonly CSSStartingStyleRule: false
    readonly CSSStyleDeclaration: false
    readonly CSSStyleRule: false
    readonly CSSStyleSheet: false
    readonly CSSStyleValue: false
    readonly CSSSupportsRule: false
    readonly CSSTransformComponent: false
    readonly CSSTransformValue: false
    readonly CSSTransition: false
    readonly CSSTranslate: false
    readonly CSSUnitValue: false
    readonly CSSUnparsedValue: false
    readonly CSSVariableReferenceValue: false
    readonly CSSViewTransitionRule: false
    readonly currentFrame: false
    readonly currentTime: false
    readonly CustomElementRegistry: false
    readonly customElements: false
    readonly CustomStateSet: false
    readonly DataTransfer: false
    readonly DataTransferItem: false
    readonly DataTransferItemList: false
    readonly DelayNode: false
    readonly DelegatedInkTrailPresenter: false
    readonly DeviceMotionEvent: false
    readonly DeviceMotionEventAcceleration: false
    readonly DeviceMotionEventRotationRate: false
    readonly DeviceOrientationEvent: false
    readonly devicePixelRatio: false
    readonly DevicePosture: false
    readonly dispatchEvent: false
    readonly document: false
    readonly Document: false
    readonly DocumentFragment: false
    readonly documentPictureInPicture: false
    readonly DocumentPictureInPicture: false
    readonly DocumentPictureInPictureEvent: false
    readonly DocumentTimeline: false
    readonly DocumentType: false
    readonly DOMError: false
    readonly DOMImplementation: false
    readonly DOMMatrix: false
    readonly DOMMatrixReadOnly: false
    readonly DOMParser: false
    readonly DOMPoint: false
    readonly DOMPointReadOnly: false
    readonly DOMQuad: false
    readonly DOMRect: false
    readonly DOMRectList: false
    readonly DOMRectReadOnly: false
    readonly DOMStringList: false
    readonly DOMStringMap: false
    readonly DOMTokenList: false
    readonly DragEvent: false
    readonly DynamicsCompressorNode: false
    readonly EditContext: false
    readonly Element: false
    readonly ElementInternals: false
    readonly EncodedAudioChunk: false
    readonly EncodedVideoChunk: false
    readonly ErrorEvent: false
    readonly event: false
    readonly EventCounts: false
    readonly EventSource: false
    readonly external: false
    readonly External: false
    readonly EyeDropper: false
    readonly FeaturePolicy: false
    readonly FederatedCredential: false
    readonly fence: false
    readonly Fence: false
    readonly FencedFrameConfig: false
    readonly fetchLater: false
    readonly FetchLaterResult: false
    readonly FileList: false
    readonly FileReader: false
    readonly FileSystem: false
    readonly FileSystemDirectoryEntry: false
    readonly FileSystemDirectoryHandle: false
    readonly FileSystemDirectoryReader: false
    readonly FileSystemEntry: false
    readonly FileSystemFileEntry: false
    readonly FileSystemFileHandle: false
    readonly FileSystemHandle: false
    readonly FileSystemObserver: false
    readonly FileSystemWritableFileStream: false
    readonly find: false
    readonly focus: false
    readonly FocusEvent: false
    readonly FontData: false
    readonly FontFace: false
    readonly FontFaceSet: false
    readonly FontFaceSetLoadEvent: false
    readonly FormDataEvent: false
    readonly FragmentDirective: false
    readonly frameElement: false
    readonly frames: false
    readonly GainNode: false
    readonly Gamepad: false
    readonly GamepadAxisMoveEvent: false
    readonly GamepadButton: false
    readonly GamepadButtonEvent: false
    readonly GamepadEvent: false
    readonly GamepadHapticActuator: false
    readonly GamepadPose: false
    readonly Geolocation: false
    readonly GeolocationCoordinates: false
    readonly GeolocationPosition: false
    readonly GeolocationPositionError: false
    readonly getComputedStyle: false
    readonly getScreenDetails: false
    readonly getSelection: false
    readonly GPU: false
    readonly GPUAdapter: false
    readonly GPUAdapterInfo: false
    readonly GPUBindGroup: false
    readonly GPUBindGroupLayout: false
    readonly GPUBuffer: false
    readonly GPUBufferUsage: false
    readonly GPUCanvasContext: false
    readonly GPUColorWrite: false
    readonly GPUCommandBuffer: false
    readonly GPUCommandEncoder: false
    readonly GPUCompilationInfo: false
    readonly GPUCompilationMessage: false
    readonly GPUComputePassEncoder: false
    readonly GPUComputePipeline: false
    readonly GPUDevice: false
    readonly GPUDeviceLostInfo: false
    readonly GPUError: false
    readonly GPUExternalTexture: false
    readonly GPUInternalError: false
    readonly GPUMapMode: false
    readonly GPUOutOfMemoryError: false
    readonly GPUPipelineError: false
    readonly GPUPipelineLayout: false
    readonly GPUQuerySet: false
    readonly GPUQueue: false
    readonly GPURenderBundle: false
    readonly GPURenderBundleEncoder: false
    readonly GPURenderPassEncoder: false
    readonly GPURenderPipeline: false
    readonly GPUSampler: false
    readonly GPUShaderModule: false
    readonly GPUShaderStage: false
    readonly GPUSupportedFeatures: false
    readonly GPUSupportedLimits: false
    readonly GPUTexture: false
    readonly GPUTextureUsage: false
    readonly GPUTextureView: false
    readonly GPUUncapturedErrorEvent: false
    readonly GPUValidationError: false
    readonly GravitySensor: false
    readonly Gyroscope: false
    readonly HashChangeEvent: false
    readonly HID: false
    readonly HIDConnectionEvent: false
    readonly HIDDevice: false
    readonly HIDInputReportEvent: false
    readonly Highlight: false
    readonly HighlightRegistry: false
    readonly history: false
    readonly History: false
    readonly HTMLAllCollection: false
    readonly HTMLAnchorElement: false
    readonly HTMLAreaElement: false
    readonly HTMLAudioElement: false
    readonly HTMLBaseElement: false
    readonly HTMLBodyElement: false
    readonly HTMLBRElement: false
    readonly HTMLButtonElement: false
    readonly HTMLCanvasElement: false
    readonly HTMLCollection: false
    readonly HTMLDataElement: false
    readonly HTMLDataListElement: false
    readonly HTMLDetailsElement: false
    readonly HTMLDialogElement: false
    readonly HTMLDirectoryElement: false
    readonly HTMLDivElement: false
    readonly HTMLDListElement: false
    readonly HTMLDocument: false
    readonly HTMLElement: false
    readonly HTMLEmbedElement: false
    readonly HTMLFencedFrameElement: false
    readonly HTMLFieldSetElement: false
    readonly HTMLFontElement: false
    readonly HTMLFormControlsCollection: false
    readonly HTMLFormElement: false
    readonly HTMLFrameElement: false
    readonly HTMLFrameSetElement: false
    readonly HTMLHeadElement: false
    readonly HTMLHeadingElement: false
    readonly HTMLHRElement: false
    readonly HTMLHtmlElement: false
    readonly HTMLIFrameElement: false
    readonly HTMLImageElement: false
    readonly HTMLInputElement: false
    readonly HTMLLabelElement: false
    readonly HTMLLegendElement: false
    readonly HTMLLIElement: false
    readonly HTMLLinkElement: false
    readonly HTMLMapElement: false
    readonly HTMLMarqueeElement: false
    readonly HTMLMediaElement: false
    readonly HTMLMenuElement: false
    readonly HTMLMetaElement: false
    readonly HTMLMeterElement: false
    readonly HTMLModElement: false
    readonly HTMLObjectElement: false
    readonly HTMLOListElement: false
    readonly HTMLOptGroupElement: false
    readonly HTMLOptionElement: false
    readonly HTMLOptionsCollection: false
    readonly HTMLOutputElement: false
    readonly HTMLParagraphElement: false
    readonly HTMLParamElement: false
    readonly HTMLPictureElement: false
    readonly HTMLPreElement: false
    readonly HTMLProgressElement: false
    readonly HTMLQuoteElement: false
    readonly HTMLScriptElement: false
    readonly HTMLSelectedContentElement: false
    readonly HTMLSelectElement: false
    readonly HTMLSlotElement: false
    readonly HTMLSourceElement: false
    readonly HTMLSpanElement: false
    readonly HTMLStyleElement: false
    readonly HTMLTableCaptionElement: false
    readonly HTMLTableCellElement: false
    readonly HTMLTableColElement: false
    readonly HTMLTableElement: false
    readonly HTMLTableRowElement: false
    readonly HTMLTableSectionElement: false
    readonly HTMLTemplateElement: false
    readonly HTMLTextAreaElement: false
    readonly HTMLTimeElement: false
    readonly HTMLTitleElement: false
    readonly HTMLTrackElement: false
    readonly HTMLUListElement: false
    readonly HTMLUnknownElement: false
    readonly HTMLVideoElement: false
    readonly IDBCursor: false
    readonly IDBCursorWithValue: false
    readonly IDBDatabase: false
    readonly IDBFactory: false
    readonly IDBIndex: false
    readonly IDBKeyRange: false
    readonly IDBObjectStore: false
    readonly IDBOpenDBRequest: false
    readonly IDBRequest: false
    readonly IDBTransaction: false
    readonly IDBVersionChangeEvent: false
    readonly IdentityCredential: false
    readonly IdentityCredentialError: false
    readonly IdentityProvider: false
    readonly IdleDeadline: false
    readonly IdleDetector: false
    readonly IIRFilterNode: false
    readonly Image: false
    readonly ImageBitmap: false
    readonly ImageBitmapRenderingContext: false
    readonly ImageCapture: false
    readonly ImageData: false
    readonly ImageDecoder: false
    readonly ImageTrack: false
    readonly ImageTrackList: false
    readonly indexedDB: false
    readonly Ink: false
    readonly innerHeight: false
    readonly innerWidth: false
    readonly InputDeviceCapabilities: false
    readonly InputDeviceInfo: false
    readonly InputEvent: false
    readonly IntersectionObserver: false
    readonly IntersectionObserverEntry: false
    readonly isSecureContext: false
    readonly Keyboard: false
    readonly KeyboardEvent: false
    readonly KeyboardLayoutMap: false
    readonly KeyframeEffect: false
    readonly LanguageDetector: false
    readonly LargestContentfulPaint: false
    readonly LaunchParams: false
    readonly launchQueue: false
    readonly LaunchQueue: false
    readonly LayoutShift: false
    readonly LayoutShiftAttribution: false
    readonly length: false
    readonly LinearAccelerationSensor: false
    readonly localStorage: false
    readonly location: true
    readonly Location: false
    readonly locationbar: false
    readonly Lock: false
    readonly LockManager: false
    readonly matchMedia: false
    readonly MathMLElement: false
    readonly MediaCapabilities: false
    readonly MediaCapabilitiesInfo: false
    readonly MediaDeviceInfo: false
    readonly MediaDevices: false
    readonly MediaElementAudioSourceNode: false
    readonly MediaEncryptedEvent: false
    readonly MediaError: false
    readonly MediaKeyError: false
    readonly MediaKeyMessageEvent: false
    readonly MediaKeys: false
    readonly MediaKeySession: false
    readonly MediaKeyStatusMap: false
    readonly MediaKeySystemAccess: false
    readonly MediaList: false
    readonly MediaMetadata: false
    readonly MediaQueryList: false
    readonly MediaQueryListEvent: false
    readonly MediaRecorder: false
    readonly MediaRecorderErrorEvent: false
    readonly MediaSession: false
    readonly MediaSource: false
    readonly MediaSourceHandle: false
    readonly MediaStream: false
    readonly MediaStreamAudioDestinationNode: false
    readonly MediaStreamAudioSourceNode: false
    readonly MediaStreamEvent: false
    readonly MediaStreamTrack: false
    readonly MediaStreamTrackAudioSourceNode: false
    readonly MediaStreamTrackAudioStats: false
    readonly MediaStreamTrackEvent: false
    readonly MediaStreamTrackGenerator: false
    readonly MediaStreamTrackProcessor: false
    readonly MediaStreamTrackVideoStats: false
    readonly menubar: false
    readonly MIDIAccess: false
    readonly MIDIConnectionEvent: false
    readonly MIDIInput: false
    readonly MIDIInputMap: false
    readonly MIDIMessageEvent: false
    readonly MIDIOutput: false
    readonly MIDIOutputMap: false
    readonly MIDIPort: false
    readonly MimeType: false
    readonly MimeTypeArray: false
    readonly model: false
    readonly ModelGenericSession: false
    readonly ModelManager: false
    readonly MouseEvent: false
    readonly moveBy: false
    readonly moveTo: false
    readonly MutationEvent: false
    readonly MutationObserver: false
    readonly MutationRecord: false
    readonly name: false
    readonly NamedNodeMap: false
    readonly NavigateEvent: false
    readonly navigation: false
    readonly Navigation: false
    readonly NavigationActivation: false
    readonly NavigationCurrentEntryChangeEvent: false
    readonly NavigationDestination: false
    readonly NavigationHistoryEntry: false
    readonly NavigationPreloadManager: false
    readonly NavigationTransition: false
    readonly NavigatorLogin: false
    readonly NavigatorManagedData: false
    readonly NavigatorUAData: false
    readonly NetworkInformation: false
    readonly Node: false
    readonly NodeFilter: false
    readonly NodeIterator: false
    readonly NodeList: false
    readonly Notification: false
    readonly NotifyPaintEvent: false
    readonly NotRestoredReasonDetails: false
    readonly NotRestoredReasons: false
    readonly Observable: false
    readonly OfflineAudioCompletionEvent: false
    readonly OfflineAudioContext: false
    readonly offscreenBuffering: false
    readonly OffscreenCanvas: false
    readonly OffscreenCanvasRenderingContext2D: false
    readonly onabort: true
    readonly onafterprint: true
    readonly onanimationcancel: true
    readonly onanimationend: true
    readonly onanimationiteration: true
    readonly onanimationstart: true
    readonly onappinstalled: true
    readonly onauxclick: true
    readonly onbeforeinput: true
    readonly onbeforeinstallprompt: true
    readonly onbeforematch: true
    readonly onbeforeprint: true
    readonly onbeforetoggle: true
    readonly onbeforeunload: true
    readonly onbeforexrselect: true
    readonly onblur: true
    readonly oncancel: true
    readonly oncanplay: true
    readonly oncanplaythrough: true
    readonly onchange: true
    readonly onclick: true
    readonly onclose: true
    readonly oncommand: true
    readonly oncontentvisibilityautostatechange: true
    readonly oncontextlost: true
    readonly oncontextmenu: true
    readonly oncontextrestored: true
    readonly oncopy: true
    readonly oncuechange: true
    readonly oncut: true
    readonly ondblclick: true
    readonly ondevicemotion: true
    readonly ondeviceorientation: true
    readonly ondeviceorientationabsolute: true
    readonly ondrag: true
    readonly ondragend: true
    readonly ondragenter: true
    readonly ondragleave: true
    readonly ondragover: true
    readonly ondragstart: true
    readonly ondrop: true
    readonly ondurationchange: true
    readonly onemptied: true
    readonly onended: true
    readonly onerror: true
    readonly onfocus: true
    readonly onformdata: true
    readonly ongamepadconnected: true
    readonly ongamepaddisconnected: true
    readonly ongotpointercapture: true
    readonly onhashchange: true
    readonly oninput: true
    readonly oninvalid: true
    readonly onkeydown: true
    readonly onkeypress: true
    readonly onkeyup: true
    readonly onlanguagechange: true
    readonly onload: true
    readonly onloadeddata: true
    readonly onloadedmetadata: true
    readonly onloadstart: true
    readonly onlostpointercapture: true
    readonly onmessage: true
    readonly onmessageerror: true
    readonly onmousedown: true
    readonly onmouseenter: true
    readonly onmouseleave: true
    readonly onmousemove: true
    readonly onmouseout: true
    readonly onmouseover: true
    readonly onmouseup: true
    readonly onmousewheel: true
    readonly onoffline: true
    readonly ononline: true
    readonly onpagehide: true
    readonly onpagereveal: true
    readonly onpageshow: true
    readonly onpageswap: true
    readonly onpaste: true
    readonly onpause: true
    readonly onplay: true
    readonly onplaying: true
    readonly onpointercancel: true
    readonly onpointerdown: true
    readonly onpointerenter: true
    readonly onpointerleave: true
    readonly onpointermove: true
    readonly onpointerout: true
    readonly onpointerover: true
    readonly onpointerrawupdate: true
    readonly onpointerup: true
    readonly onpopstate: true
    readonly onprogress: true
    readonly onratechange: true
    readonly onrejectionhandled: true
    readonly onreset: true
    readonly onresize: true
    readonly onscroll: true
    readonly onscrollend: true
    readonly onscrollsnapchange: true
    readonly onscrollsnapchanging: true
    readonly onsearch: true
    readonly onsecuritypolicyviolation: true
    readonly onseeked: true
    readonly onseeking: true
    readonly onselect: true
    readonly onselectionchange: true
    readonly onselectstart: true
    readonly onslotchange: true
    readonly onstalled: true
    readonly onstorage: true
    readonly onsubmit: true
    readonly onsuspend: true
    readonly ontimeupdate: true
    readonly ontoggle: true
    readonly ontransitioncancel: true
    readonly ontransitionend: true
    readonly ontransitionrun: true
    readonly ontransitionstart: true
    readonly onunhandledrejection: true
    readonly onunload: true
    readonly onvolumechange: true
    readonly onwaiting: true
    readonly onwheel: true
    readonly open: false
    readonly opener: false
    readonly Option: false
    readonly OrientationSensor: false
    readonly origin: false
    readonly originAgentCluster: false
    readonly OscillatorNode: false
    readonly OTPCredential: false
    readonly outerHeight: false
    readonly outerWidth: false
    readonly OverconstrainedError: false
    readonly PageRevealEvent: false
    readonly PageSwapEvent: false
    readonly PageTransitionEvent: false
    readonly pageXOffset: false
    readonly pageYOffset: false
    readonly PannerNode: false
    readonly parent: false
    readonly PasswordCredential: false
    readonly Path2D: false
    readonly PaymentAddress: false
    readonly PaymentManager: false
    readonly PaymentMethodChangeEvent: false
    readonly PaymentRequest: false
    readonly PaymentRequestUpdateEvent: false
    readonly PaymentResponse: false
    readonly PerformanceElementTiming: false
    readonly PerformanceEventTiming: false
    readonly PerformanceLongAnimationFrameTiming: false
    readonly PerformanceLongTaskTiming: false
    readonly PerformanceNavigation: false
    readonly PerformanceNavigationTiming: false
    readonly PerformancePaintTiming: false
    readonly PerformanceScriptTiming: false
    readonly PerformanceServerTiming: false
    readonly PerformanceTiming: false
    readonly PeriodicSyncManager: false
    readonly PeriodicWave: false
    readonly Permissions: false
    readonly PermissionStatus: false
    readonly PERSISTENT: false
    readonly personalbar: false
    readonly PictureInPictureEvent: false
    readonly PictureInPictureWindow: false
    readonly Plugin: false
    readonly PluginArray: false
    readonly PointerEvent: false
    readonly PopStateEvent: false
    readonly postMessage: false
    readonly Presentation: false
    readonly PresentationAvailability: false
    readonly PresentationConnection: false
    readonly PresentationConnectionAvailableEvent: false
    readonly PresentationConnectionCloseEvent: false
    readonly PresentationConnectionList: false
    readonly PresentationReceiver: false
    readonly PresentationRequest: false
    readonly PressureObserver: false
    readonly PressureRecord: false
    readonly print: false
    readonly ProcessingInstruction: false
    readonly Profiler: false
    readonly ProgressEvent: false
    readonly PromiseRejectionEvent: false
    readonly prompt: false
    readonly ProtectedAudience: false
    readonly PublicKeyCredential: false
    readonly PushManager: false
    readonly PushSubscription: false
    readonly PushSubscriptionOptions: false
    readonly queryLocalFonts: false
    readonly RadioNodeList: false
    readonly Range: false
    readonly registerProcessor: false
    readonly RelativeOrientationSensor: false
    readonly RemotePlayback: false
    readonly removeEventListener: false
    readonly ReportBody: false
    readonly reportError: false
    readonly ReportingObserver: false
    readonly requestAnimationFrame: false
    readonly requestIdleCallback: false
    readonly resizeBy: false
    readonly ResizeObserver: false
    readonly ResizeObserverEntry: false
    readonly ResizeObserverSize: false
    readonly resizeTo: false
    readonly RestrictionTarget: false
    readonly RTCCertificate: false
    readonly RTCDataChannel: false
    readonly RTCDataChannelEvent: false
    readonly RTCDtlsTransport: false
    readonly RTCDTMFSender: false
    readonly RTCDTMFToneChangeEvent: false
    readonly RTCEncodedAudioFrame: false
    readonly RTCEncodedVideoFrame: false
    readonly RTCError: false
    readonly RTCErrorEvent: false
    readonly RTCIceCandidate: false
    readonly RTCIceTransport: false
    readonly RTCPeerConnection: false
    readonly RTCPeerConnectionIceErrorEvent: false
    readonly RTCPeerConnectionIceEvent: false
    readonly RTCRtpReceiver: false
    readonly RTCRtpScriptTransform: false
    readonly RTCRtpSender: false
    readonly RTCRtpTransceiver: false
    readonly RTCSctpTransport: false
    readonly RTCSessionDescription: false
    readonly RTCStatsReport: false
    readonly RTCTrackEvent: false
    readonly sampleRate: false
    readonly scheduler: false
    readonly Scheduler: false
    readonly Scheduling: false
    readonly screen: false
    readonly Screen: false
    readonly ScreenDetailed: false
    readonly ScreenDetails: false
    readonly screenLeft: false
    readonly ScreenOrientation: false
    readonly screenTop: false
    readonly screenX: false
    readonly screenY: false
    readonly ScriptProcessorNode: false
    readonly scroll: false
    readonly scrollbars: false
    readonly scrollBy: false
    readonly ScrollTimeline: false
    readonly scrollTo: false
    readonly scrollX: false
    readonly scrollY: false
    readonly SecurityPolicyViolationEvent: false
    readonly Selection: false
    readonly self: false
    readonly Sensor: false
    readonly SensorErrorEvent: false
    readonly Serial: false
    readonly SerialPort: false
    readonly ServiceWorker: false
    readonly ServiceWorkerContainer: false
    readonly ServiceWorkerRegistration: false
    readonly sessionStorage: false
    readonly ShadowRoot: false
    readonly sharedStorage: false
    readonly SharedStorage: false
    readonly SharedStorageAppendMethod: false
    readonly SharedStorageClearMethod: false
    readonly SharedStorageDeleteMethod: false
    readonly SharedStorageModifierMethod: false
    readonly SharedStorageSetMethod: false
    readonly SharedStorageWorklet: false
    readonly SharedWorker: false
    readonly showDirectoryPicker: false
    readonly showOpenFilePicker: false
    readonly showSaveFilePicker: false
    readonly SnapEvent: false
    readonly SourceBuffer: false
    readonly SourceBufferList: false
    readonly speechSynthesis: false
    readonly SpeechSynthesis: false
    readonly SpeechSynthesisErrorEvent: false
    readonly SpeechSynthesisEvent: false
    readonly SpeechSynthesisUtterance: false
    readonly SpeechSynthesisVoice: false
    readonly StaticRange: false
    readonly status: false
    readonly statusbar: false
    readonly StereoPannerNode: false
    readonly stop: false
    readonly Storage: false
    readonly StorageBucket: false
    readonly StorageBucketManager: false
    readonly StorageEvent: false
    readonly StorageManager: false
    readonly styleMedia: false
    readonly StylePropertyMap: false
    readonly StylePropertyMapReadOnly: false
    readonly StyleSheet: false
    readonly StyleSheetList: false
    readonly SubmitEvent: false
    readonly Subscriber: false
    readonly SVGAElement: false
    readonly SVGAngle: false
    readonly SVGAnimatedAngle: false
    readonly SVGAnimatedBoolean: false
    readonly SVGAnimatedEnumeration: false
    readonly SVGAnimatedInteger: false
    readonly SVGAnimatedLength: false
    readonly SVGAnimatedLengthList: false
    readonly SVGAnimatedNumber: false
    readonly SVGAnimatedNumberList: false
    readonly SVGAnimatedPreserveAspectRatio: false
    readonly SVGAnimatedRect: false
    readonly SVGAnimatedString: false
    readonly SVGAnimatedTransformList: false
    readonly SVGAnimateElement: false
    readonly SVGAnimateMotionElement: false
    readonly SVGAnimateTransformElement: false
    readonly SVGAnimationElement: false
    readonly SVGCircleElement: false
    readonly SVGClipPathElement: false
    readonly SVGComponentTransferFunctionElement: false
    readonly SVGDefsElement: false
    readonly SVGDescElement: false
    readonly SVGElement: false
    readonly SVGEllipseElement: false
    readonly SVGFEBlendElement: false
    readonly SVGFEColorMatrixElement: false
    readonly SVGFEComponentTransferElement: false
    readonly SVGFECompositeElement: false
    readonly SVGFEConvolveMatrixElement: false
    readonly SVGFEDiffuseLightingElement: false
    readonly SVGFEDisplacementMapElement: false
    readonly SVGFEDistantLightElement: false
    readonly SVGFEDropShadowElement: false
    readonly SVGFEFloodElement: false
    readonly SVGFEFuncAElement: false
    readonly SVGFEFuncBElement: false
    readonly SVGFEFuncGElement: false
    readonly SVGFEFuncRElement: false
    readonly SVGFEGaussianBlurElement: false
    readonly SVGFEImageElement: false
    readonly SVGFEMergeElement: false
    readonly SVGFEMergeNodeElement: false
    readonly SVGFEMorphologyElement: false
    readonly SVGFEOffsetElement: false
    readonly SVGFEPointLightElement: false
    readonly SVGFESpecularLightingElement: false
    readonly SVGFESpotLightElement: false
    readonly SVGFETileElement: false
    readonly SVGFETurbulenceElement: false
    readonly SVGFilterElement: false
    readonly SVGForeignObjectElement: false
    readonly SVGGElement: false
    readonly SVGGeometryElement: false
    readonly SVGGradientElement: false
    readonly SVGGraphicsElement: false
    readonly SVGImageElement: false
    readonly SVGLength: false
    readonly SVGLengthList: false
    readonly SVGLinearGradientElement: false
    readonly SVGLineElement: false
    readonly SVGMarkerElement: false
    readonly SVGMaskElement: false
    readonly SVGMatrix: false
    readonly SVGMetadataElement: false
    readonly SVGMPathElement: false
    readonly SVGNumber: false
    readonly SVGNumberList: false
    readonly SVGPathElement: false
    readonly SVGPatternElement: false
    readonly SVGPoint: false
    readonly SVGPointList: false
    readonly SVGPolygonElement: false
    readonly SVGPolylineElement: false
    readonly SVGPreserveAspectRatio: false
    readonly SVGRadialGradientElement: false
    readonly SVGRect: false
    readonly SVGRectElement: false
    readonly SVGScriptElement: false
    readonly SVGSetElement: false
    readonly SVGStopElement: false
    readonly SVGStringList: false
    readonly SVGStyleElement: false
    readonly SVGSVGElement: false
    readonly SVGSwitchElement: false
    readonly SVGSymbolElement: false
    readonly SVGTextContentElement: false
    readonly SVGTextElement: false
    readonly SVGTextPathElement: false
    readonly SVGTextPositioningElement: false
    readonly SVGTitleElement: false
    readonly SVGTransform: false
    readonly SVGTransformList: false
    readonly SVGTSpanElement: false
    readonly SVGUnitTypes: false
    readonly SVGUseElement: false
    readonly SVGViewElement: false
    readonly SyncManager: false
    readonly TaskAttributionTiming: false
    readonly TaskController: false
    readonly TaskPriorityChangeEvent: false
    readonly TaskSignal: false
    readonly TEMPORARY: false
    readonly Text: false
    readonly TextEvent: false
    readonly TextFormat: false
    readonly TextFormatUpdateEvent: false
    readonly TextMetrics: false
    readonly TextTrack: false
    readonly TextTrackCue: false
    readonly TextTrackCueList: false
    readonly TextTrackList: false
    readonly TextUpdateEvent: false
    readonly TimeEvent: false
    readonly TimeRanges: false
    readonly ToggleEvent: false
    readonly toolbar: false
    readonly top: false
    readonly Touch: false
    readonly TouchEvent: false
    readonly TouchList: false
    readonly TrackEvent: false
    readonly TransitionEvent: false
    readonly TreeWalker: false
    readonly TrustedHTML: false
    readonly TrustedScript: false
    readonly TrustedScriptURL: false
    readonly TrustedTypePolicy: false
    readonly TrustedTypePolicyFactory: false
    readonly trustedTypes: false
    readonly UIEvent: false
    readonly USB: false
    readonly USBAlternateInterface: false
    readonly USBConfiguration: false
    readonly USBConnectionEvent: false
    readonly USBDevice: false
    readonly USBEndpoint: false
    readonly USBInterface: false
    readonly USBInTransferResult: false
    readonly USBIsochronousInTransferPacket: false
    readonly USBIsochronousInTransferResult: false
    readonly USBIsochronousOutTransferPacket: false
    readonly USBIsochronousOutTransferResult: false
    readonly USBOutTransferResult: false
    readonly UserActivation: false
    readonly ValidityState: false
    readonly VideoColorSpace: false
    readonly VideoDecoder: false
    readonly VideoEncoder: false
    readonly VideoFrame: false
    readonly VideoPlaybackQuality: false
    readonly ViewTimeline: false
    readonly ViewTransition: false
    readonly ViewTransitionTypeSet: false
    readonly VirtualKeyboard: false
    readonly VirtualKeyboardGeometryChangeEvent: false
    readonly VisibilityStateEntry: false
    readonly visualViewport: false
    readonly VisualViewport: false
    readonly VTTCue: false
    readonly VTTRegion: false
    readonly WakeLock: false
    readonly WakeLockSentinel: false
    readonly WaveShaperNode: false
    readonly WebGL2RenderingContext: false
    readonly WebGLActiveInfo: false
    readonly WebGLBuffer: false
    readonly WebGLContextEvent: false
    readonly WebGLFramebuffer: false
    readonly WebGLObject: false
    readonly WebGLProgram: false
    readonly WebGLQuery: false
    readonly WebGLRenderbuffer: false
    readonly WebGLRenderingContext: false
    readonly WebGLSampler: false
    readonly WebGLShader: false
    readonly WebGLShaderPrecisionFormat: false
    readonly WebGLSync: false
    readonly WebGLTexture: false
    readonly WebGLTransformFeedback: false
    readonly WebGLUniformLocation: false
    readonly WebGLVertexArrayObject: false
    readonly WebSocketError: false
    readonly WebSocketStream: false
    readonly WebTransport: false
    readonly WebTransportBidirectionalStream: false
    readonly WebTransportDatagramDuplexStream: false
    readonly WebTransportError: false
    readonly WebTransportReceiveStream: false
    readonly WebTransportSendStream: false
    readonly WGSLLanguageFeatures: false
    readonly WheelEvent: false
    readonly when: false
    readonly window: false
    readonly Window: false
    readonly WindowControlsOverlay: false
    readonly WindowControlsOverlayGeometryChangeEvent: false
    readonly Worker: false
    readonly Worklet: false
    readonly WorkletGlobalScope: false
    readonly XMLDocument: false
    readonly XMLHttpRequest: false
    readonly XMLHttpRequestEventTarget: false
    readonly XMLHttpRequestUpload: false
    readonly XMLSerializer: false
    readonly XPathEvaluator: false
    readonly XPathExpression: false
    readonly XPathResult: false
    readonly XRAnchor: false
    readonly XRAnchorSet: false
    readonly XRBoundedReferenceSpace: false
    readonly XRCamera: false
    readonly XRCPUDepthInformation: false
    readonly XRDepthInformation: false
    readonly XRDOMOverlayState: false
    readonly XRFrame: false
    readonly XRHand: false
    readonly XRHitTestResult: false
    readonly XRHitTestSource: false
    readonly XRInputSource: false
    readonly XRInputSourceArray: false
    readonly XRInputSourceEvent: false
    readonly XRInputSourcesChangeEvent: false
    readonly XRJointPose: false
    readonly XRJointSpace: false
    readonly XRLayer: false
    readonly XRLightEstimate: false
    readonly XRLightProbe: false
    readonly XRPose: false
    readonly XRRay: false
    readonly XRReferenceSpace: false
    readonly XRReferenceSpaceEvent: false
    readonly XRRenderState: false
    readonly XRRigidTransform: false
    readonly XRSession: false
    readonly XRSessionEvent: false
    readonly XRSpace: false
    readonly XRSystem: false
    readonly XRTransientInputHitTestResult: false
    readonly XRTransientInputHitTestSource: false
    readonly XRView: false
    readonly XRViewerPose: false
    readonly XRViewport: false
    readonly XRWebGLBinding: false
    readonly XRWebGLDepthInformation: false
    readonly XRWebGLLayer: false
    readonly XSLTProcessor: false
  } & {
    readonly suite: 'writable'
    readonly test: 'writable'
    readonly chai: 'writable'
    readonly describe: 'writable'
    readonly it: 'writable'
    readonly expectTypeOf: 'writable'
    readonly assertType: 'writable'
    readonly expect: 'writable'
    readonly assert: 'writable'
    readonly vitest: 'writable'
    readonly vi: 'writable'
    readonly beforeAll: 'writable'
    readonly afterAll: 'writable'
    readonly beforeEach: 'writable'
    readonly afterEach: 'writable'
    readonly onTestFailed: 'writable'
    readonly onTestFinished: 'writable'
  } as {
    readonly AbortController: false
    readonly AbortSignal: false
    readonly AsyncDisposableStack: false
    readonly atob: false
    readonly Blob: false
    readonly BroadcastChannel: false
    readonly btoa: false
    readonly Buffer: false
    readonly ByteLengthQueuingStrategy: false
    readonly clearImmediate: false
    readonly clearInterval: false
    readonly clearTimeout: false
    readonly CloseEvent: false
    readonly CompressionStream: false
    readonly console: false
    readonly CountQueuingStrategy: false
    readonly crypto: false
    readonly Crypto: false
    readonly CryptoKey: false
    readonly CustomEvent: false
    readonly DecompressionStream: false
    readonly DisposableStack: false
    readonly DOMException: false
    readonly Event: false
    readonly EventTarget: false
    readonly fetch: false
    readonly File: false
    readonly FormData: false
    readonly global: false
    readonly Headers: false
    readonly MessageChannel: false
    readonly MessageEvent: false
    readonly MessagePort: false
    readonly navigator: false
    readonly Navigator: false
    readonly performance: false
    readonly Performance: false
    readonly PerformanceEntry: false
    readonly PerformanceMark: false
    readonly PerformanceMeasure: false
    readonly PerformanceObserver: false
    readonly PerformanceObserverEntryList: false
    readonly PerformanceResourceTiming: false
    readonly process: false
    readonly queueMicrotask: false
    readonly ReadableByteStreamController: false
    readonly ReadableStream: false
    readonly ReadableStreamBYOBReader: false
    readonly ReadableStreamBYOBRequest: false
    readonly ReadableStreamDefaultController: false
    readonly ReadableStreamDefaultReader: false
    readonly Request: false
    readonly Response: false
    readonly setImmediate: false
    readonly setInterval: false
    readonly setTimeout: false
    readonly structuredClone: false
    readonly SubtleCrypto: false
    readonly SuppressedError: false
    readonly TextDecoder: false
    readonly TextDecoderStream: false
    readonly TextEncoder: false
    readonly TextEncoderStream: false
    readonly TransformStream: false
    readonly TransformStreamDefaultController: false
    readonly URL: false
    readonly URLPattern: false
    readonly URLSearchParams: false
    readonly WebAssembly: false
    readonly WebSocket: false
    readonly WritableStream: false
    readonly WritableStreamDefaultController: false
    readonly WritableStreamDefaultWriter: false
    readonly __dirname: false
    readonly __filename: false
    readonly exports: true
    readonly module: false
    readonly require: false
    readonly AbsoluteOrientationSensor: false
    readonly AbstractRange: false
    readonly Accelerometer: false
    readonly addEventListener: false
    readonly ai: false
    readonly AI: false
    readonly AICreateMonitor: false
    readonly AITextSession: false
    readonly alert: false
    readonly AnalyserNode: false
    readonly Animation: false
    readonly AnimationEffect: false
    readonly AnimationEvent: false
    readonly AnimationPlaybackEvent: false
    readonly AnimationTimeline: false
    readonly Attr: false
    readonly Audio: false
    readonly AudioBuffer: false
    readonly AudioBufferSourceNode: false
    readonly AudioContext: false
    readonly AudioData: false
    readonly AudioDecoder: false
    readonly AudioDestinationNode: false
    readonly AudioEncoder: false
    readonly AudioListener: false
    readonly AudioNode: false
    readonly AudioParam: false
    readonly AudioParamMap: false
    readonly AudioProcessingEvent: false
    readonly AudioScheduledSourceNode: false
    readonly AudioSinkInfo: false
    readonly AudioWorklet: false
    readonly AudioWorkletGlobalScope: false
    readonly AudioWorkletNode: false
    readonly AudioWorkletProcessor: false
    readonly AuthenticatorAssertionResponse: false
    readonly AuthenticatorAttestationResponse: false
    readonly AuthenticatorResponse: false
    readonly BackgroundFetchManager: false
    readonly BackgroundFetchRecord: false
    readonly BackgroundFetchRegistration: false
    readonly BarcodeDetector: false
    readonly BarProp: false
    readonly BaseAudioContext: false
    readonly BatteryManager: false
    readonly BeforeUnloadEvent: false
    readonly BiquadFilterNode: false
    readonly BlobEvent: false
    readonly Bluetooth: false
    readonly BluetoothCharacteristicProperties: false
    readonly BluetoothDevice: false
    readonly BluetoothRemoteGATTCharacteristic: false
    readonly BluetoothRemoteGATTDescriptor: false
    readonly BluetoothRemoteGATTServer: false
    readonly BluetoothRemoteGATTService: false
    readonly BluetoothUUID: false
    readonly blur: false
    readonly BrowserCaptureMediaStreamTrack: false
    readonly Cache: false
    readonly caches: false
    readonly CacheStorage: false
    readonly cancelAnimationFrame: false
    readonly cancelIdleCallback: false
    readonly CanvasCaptureMediaStream: false
    readonly CanvasCaptureMediaStreamTrack: false
    readonly CanvasGradient: false
    readonly CanvasPattern: false
    readonly CanvasRenderingContext2D: false
    readonly CaptureController: false
    readonly CaretPosition: false
    readonly CDATASection: false
    readonly ChannelMergerNode: false
    readonly ChannelSplitterNode: false
    readonly ChapterInformation: false
    readonly CharacterBoundsUpdateEvent: false
    readonly CharacterData: false
    readonly clientInformation: false
    readonly Clipboard: false
    readonly ClipboardEvent: false
    readonly ClipboardItem: false
    readonly close: false
    readonly closed: false
    readonly CloseWatcher: false
    readonly CommandEvent: false
    readonly Comment: false
    readonly CompositionEvent: false
    readonly confirm: false
    readonly ConstantSourceNode: false
    readonly ContentVisibilityAutoStateChangeEvent: false
    readonly ConvolverNode: false
    readonly CookieChangeEvent: false
    readonly CookieDeprecationLabel: false
    readonly cookieStore: false
    readonly CookieStore: false
    readonly CookieStoreManager: false
    readonly createImageBitmap: false
    readonly Credential: false
    readonly credentialless: false
    readonly CredentialsContainer: false
    readonly CropTarget: false
    readonly crossOriginIsolated: false
    readonly CSPViolationReportBody: false
    readonly CSS: false
    readonly CSSAnimation: false
    readonly CSSConditionRule: false
    readonly CSSContainerRule: false
    readonly CSSCounterStyleRule: false
    readonly CSSFontFaceRule: false
    readonly CSSFontFeatureValuesRule: false
    readonly CSSFontPaletteValuesRule: false
    readonly CSSGroupingRule: false
    readonly CSSImageValue: false
    readonly CSSImportRule: false
    readonly CSSKeyframeRule: false
    readonly CSSKeyframesRule: false
    readonly CSSKeywordValue: false
    readonly CSSLayerBlockRule: false
    readonly CSSLayerStatementRule: false
    readonly CSSMarginRule: false
    readonly CSSMathClamp: false
    readonly CSSMathInvert: false
    readonly CSSMathMax: false
    readonly CSSMathMin: false
    readonly CSSMathNegate: false
    readonly CSSMathProduct: false
    readonly CSSMathSum: false
    readonly CSSMathValue: false
    readonly CSSMatrixComponent: false
    readonly CSSMediaRule: false
    readonly CSSNamespaceRule: false
    readonly CSSNestedDeclarations: false
    readonly CSSNumericArray: false
    readonly CSSNumericValue: false
    readonly CSSPageDescriptors: false
    readonly CSSPageRule: false
    readonly CSSPerspective: false
    readonly CSSPositionTryDescriptors: false
    readonly CSSPositionTryRule: false
    readonly CSSPositionValue: false
    readonly CSSPropertyRule: false
    readonly CSSRotate: false
    readonly CSSRule: false
    readonly CSSRuleList: false
    readonly CSSScale: false
    readonly CSSScopeRule: false
    readonly CSSSkew: false
    readonly CSSSkewX: false
    readonly CSSSkewY: false
    readonly CSSStartingStyleRule: false
    readonly CSSStyleDeclaration: false
    readonly CSSStyleRule: false
    readonly CSSStyleSheet: false
    readonly CSSStyleValue: false
    readonly CSSSupportsRule: false
    readonly CSSTransformComponent: false
    readonly CSSTransformValue: false
    readonly CSSTransition: false
    readonly CSSTranslate: false
    readonly CSSUnitValue: false
    readonly CSSUnparsedValue: false
    readonly CSSVariableReferenceValue: false
    readonly CSSViewTransitionRule: false
    readonly currentFrame: false
    readonly currentTime: false
    readonly CustomElementRegistry: false
    readonly customElements: false
    readonly CustomStateSet: false
    readonly DataTransfer: false
    readonly DataTransferItem: false
    readonly DataTransferItemList: false
    readonly DelayNode: false
    readonly DelegatedInkTrailPresenter: false
    readonly DeviceMotionEvent: false
    readonly DeviceMotionEventAcceleration: false
    readonly DeviceMotionEventRotationRate: false
    readonly DeviceOrientationEvent: false
    readonly devicePixelRatio: false
    readonly DevicePosture: false
    readonly dispatchEvent: false
    readonly document: false
    readonly Document: false
    readonly DocumentFragment: false
    readonly documentPictureInPicture: false
    readonly DocumentPictureInPicture: false
    readonly DocumentPictureInPictureEvent: false
    readonly DocumentTimeline: false
    readonly DocumentType: false
    readonly DOMError: false
    readonly DOMImplementation: false
    readonly DOMMatrix: false
    readonly DOMMatrixReadOnly: false
    readonly DOMParser: false
    readonly DOMPoint: false
    readonly DOMPointReadOnly: false
    readonly DOMQuad: false
    readonly DOMRect: false
    readonly DOMRectList: false
    readonly DOMRectReadOnly: false
    readonly DOMStringList: false
    readonly DOMStringMap: false
    readonly DOMTokenList: false
    readonly DragEvent: false
    readonly DynamicsCompressorNode: false
    readonly EditContext: false
    readonly Element: false
    readonly ElementInternals: false
    readonly EncodedAudioChunk: false
    readonly EncodedVideoChunk: false
    readonly ErrorEvent: false
    readonly event: false
    readonly EventCounts: false
    readonly EventSource: false
    readonly external: false
    readonly External: false
    readonly EyeDropper: false
    readonly FeaturePolicy: false
    readonly FederatedCredential: false
    readonly fence: false
    readonly Fence: false
    readonly FencedFrameConfig: false
    readonly fetchLater: false
    readonly FetchLaterResult: false
    readonly FileList: false
    readonly FileReader: false
    readonly FileSystem: false
    readonly FileSystemDirectoryEntry: false
    readonly FileSystemDirectoryHandle: false
    readonly FileSystemDirectoryReader: false
    readonly FileSystemEntry: false
    readonly FileSystemFileEntry: false
    readonly FileSystemFileHandle: false
    readonly FileSystemHandle: false
    readonly FileSystemObserver: false
    readonly FileSystemWritableFileStream: false
    readonly find: false
    readonly focus: false
    readonly FocusEvent: false
    readonly FontData: false
    readonly FontFace: false
    readonly FontFaceSet: false
    readonly FontFaceSetLoadEvent: false
    readonly FormDataEvent: false
    readonly FragmentDirective: false
    readonly frameElement: false
    readonly frames: false
    readonly GainNode: false
    readonly Gamepad: false
    readonly GamepadAxisMoveEvent: false
    readonly GamepadButton: false
    readonly GamepadButtonEvent: false
    readonly GamepadEvent: false
    readonly GamepadHapticActuator: false
    readonly GamepadPose: false
    readonly Geolocation: false
    readonly GeolocationCoordinates: false
    readonly GeolocationPosition: false
    readonly GeolocationPositionError: false
    readonly getComputedStyle: false
    readonly getScreenDetails: false
    readonly getSelection: false
    readonly GPU: false
    readonly GPUAdapter: false
    readonly GPUAdapterInfo: false
    readonly GPUBindGroup: false
    readonly GPUBindGroupLayout: false
    readonly GPUBuffer: false
    readonly GPUBufferUsage: false
    readonly GPUCanvasContext: false
    readonly GPUColorWrite: false
    readonly GPUCommandBuffer: false
    readonly GPUCommandEncoder: false
    readonly GPUCompilationInfo: false
    readonly GPUCompilationMessage: false
    readonly GPUComputePassEncoder: false
    readonly GPUComputePipeline: false
    readonly GPUDevice: false
    readonly GPUDeviceLostInfo: false
    readonly GPUError: false
    readonly GPUExternalTexture: false
    readonly GPUInternalError: false
    readonly GPUMapMode: false
    readonly GPUOutOfMemoryError: false
    readonly GPUPipelineError: false
    readonly GPUPipelineLayout: false
    readonly GPUQuerySet: false
    readonly GPUQueue: false
    readonly GPURenderBundle: false
    readonly GPURenderBundleEncoder: false
    readonly GPURenderPassEncoder: false
    readonly GPURenderPipeline: false
    readonly GPUSampler: false
    readonly GPUShaderModule: false
    readonly GPUShaderStage: false
    readonly GPUSupportedFeatures: false
    readonly GPUSupportedLimits: false
    readonly GPUTexture: false
    readonly GPUTextureUsage: false
    readonly GPUTextureView: false
    readonly GPUUncapturedErrorEvent: false
    readonly GPUValidationError: false
    readonly GravitySensor: false
    readonly Gyroscope: false
    readonly HashChangeEvent: false
    readonly HID: false
    readonly HIDConnectionEvent: false
    readonly HIDDevice: false
    readonly HIDInputReportEvent: false
    readonly Highlight: false
    readonly HighlightRegistry: false
    readonly history: false
    readonly History: false
    readonly HTMLAllCollection: false
    readonly HTMLAnchorElement: false
    readonly HTMLAreaElement: false
    readonly HTMLAudioElement: false
    readonly HTMLBaseElement: false
    readonly HTMLBodyElement: false
    readonly HTMLBRElement: false
    readonly HTMLButtonElement: false
    readonly HTMLCanvasElement: false
    readonly HTMLCollection: false
    readonly HTMLDataElement: false
    readonly HTMLDataListElement: false
    readonly HTMLDetailsElement: false
    readonly HTMLDialogElement: false
    readonly HTMLDirectoryElement: false
    readonly HTMLDivElement: false
    readonly HTMLDListElement: false
    readonly HTMLDocument: false
    readonly HTMLElement: false
    readonly HTMLEmbedElement: false
    readonly HTMLFencedFrameElement: false
    readonly HTMLFieldSetElement: false
    readonly HTMLFontElement: false
    readonly HTMLFormControlsCollection: false
    readonly HTMLFormElement: false
    readonly HTMLFrameElement: false
    readonly HTMLFrameSetElement: false
    readonly HTMLHeadElement: false
    readonly HTMLHeadingElement: false
    readonly HTMLHRElement: false
    readonly HTMLHtmlElement: false
    readonly HTMLIFrameElement: false
    readonly HTMLImageElement: false
    readonly HTMLInputElement: false
    readonly HTMLLabelElement: false
    readonly HTMLLegendElement: false
    readonly HTMLLIElement: false
    readonly HTMLLinkElement: false
    readonly HTMLMapElement: false
    readonly HTMLMarqueeElement: false
    readonly HTMLMediaElement: false
    readonly HTMLMenuElement: false
    readonly HTMLMetaElement: false
    readonly HTMLMeterElement: false
    readonly HTMLModElement: false
    readonly HTMLObjectElement: false
    readonly HTMLOListElement: false
    readonly HTMLOptGroupElement: false
    readonly HTMLOptionElement: false
    readonly HTMLOptionsCollection: false
    readonly HTMLOutputElement: false
    readonly HTMLParagraphElement: false
    readonly HTMLParamElement: false
    readonly HTMLPictureElement: false
    readonly HTMLPreElement: false
    readonly HTMLProgressElement: false
    readonly HTMLQuoteElement: false
    readonly HTMLScriptElement: false
    readonly HTMLSelectedContentElement: false
    readonly HTMLSelectElement: false
    readonly HTMLSlotElement: false
    readonly HTMLSourceElement: false
    readonly HTMLSpanElement: false
    readonly HTMLStyleElement: false
    readonly HTMLTableCaptionElement: false
    readonly HTMLTableCellElement: false
    readonly HTMLTableColElement: false
    readonly HTMLTableElement: false
    readonly HTMLTableRowElement: false
    readonly HTMLTableSectionElement: false
    readonly HTMLTemplateElement: false
    readonly HTMLTextAreaElement: false
    readonly HTMLTimeElement: false
    readonly HTMLTitleElement: false
    readonly HTMLTrackElement: false
    readonly HTMLUListElement: false
    readonly HTMLUnknownElement: false
    readonly HTMLVideoElement: false
    readonly IDBCursor: false
    readonly IDBCursorWithValue: false
    readonly IDBDatabase: false
    readonly IDBFactory: false
    readonly IDBIndex: false
    readonly IDBKeyRange: false
    readonly IDBObjectStore: false
    readonly IDBOpenDBRequest: false
    readonly IDBRequest: false
    readonly IDBTransaction: false
    readonly IDBVersionChangeEvent: false
    readonly IdentityCredential: false
    readonly IdentityCredentialError: false
    readonly IdentityProvider: false
    readonly IdleDeadline: false
    readonly IdleDetector: false
    readonly IIRFilterNode: false
    readonly Image: false
    readonly ImageBitmap: false
    readonly ImageBitmapRenderingContext: false
    readonly ImageCapture: false
    readonly ImageData: false
    readonly ImageDecoder: false
    readonly ImageTrack: false
    readonly ImageTrackList: false
    readonly indexedDB: false
    readonly Ink: false
    readonly innerHeight: false
    readonly innerWidth: false
    readonly InputDeviceCapabilities: false
    readonly InputDeviceInfo: false
    readonly InputEvent: false
    readonly IntersectionObserver: false
    readonly IntersectionObserverEntry: false
    readonly isSecureContext: false
    readonly Keyboard: false
    readonly KeyboardEvent: false
    readonly KeyboardLayoutMap: false
    readonly KeyframeEffect: false
    readonly LanguageDetector: false
    readonly LargestContentfulPaint: false
    readonly LaunchParams: false
    readonly launchQueue: false
    readonly LaunchQueue: false
    readonly LayoutShift: false
    readonly LayoutShiftAttribution: false
    readonly length: false
    readonly LinearAccelerationSensor: false
    readonly localStorage: false
    readonly location: true
    readonly Location: false
    readonly locationbar: false
    readonly Lock: false
    readonly LockManager: false
    readonly matchMedia: false
    readonly MathMLElement: false
    readonly MediaCapabilities: false
    readonly MediaCapabilitiesInfo: false
    readonly MediaDeviceInfo: false
    readonly MediaDevices: false
    readonly MediaElementAudioSourceNode: false
    readonly MediaEncryptedEvent: false
    readonly MediaError: false
    readonly MediaKeyError: false
    readonly MediaKeyMessageEvent: false
    readonly MediaKeys: false
    readonly MediaKeySession: false
    readonly MediaKeyStatusMap: false
    readonly MediaKeySystemAccess: false
    readonly MediaList: false
    readonly MediaMetadata: false
    readonly MediaQueryList: false
    readonly MediaQueryListEvent: false
    readonly MediaRecorder: false
    readonly MediaRecorderErrorEvent: false
    readonly MediaSession: false
    readonly MediaSource: false
    readonly MediaSourceHandle: false
    readonly MediaStream: false
    readonly MediaStreamAudioDestinationNode: false
    readonly MediaStreamAudioSourceNode: false
    readonly MediaStreamEvent: false
    readonly MediaStreamTrack: false
    readonly MediaStreamTrackAudioSourceNode: false
    readonly MediaStreamTrackAudioStats: false
    readonly MediaStreamTrackEvent: false
    readonly MediaStreamTrackGenerator: false
    readonly MediaStreamTrackProcessor: false
    readonly MediaStreamTrackVideoStats: false
    readonly menubar: false
    readonly MIDIAccess: false
    readonly MIDIConnectionEvent: false
    readonly MIDIInput: false
    readonly MIDIInputMap: false
    readonly MIDIMessageEvent: false
    readonly MIDIOutput: false
    readonly MIDIOutputMap: false
    readonly MIDIPort: false
    readonly MimeType: false
    readonly MimeTypeArray: false
    readonly model: false
    readonly ModelGenericSession: false
    readonly ModelManager: false
    readonly MouseEvent: false
    readonly moveBy: false
    readonly moveTo: false
    readonly MutationEvent: false
    readonly MutationObserver: false
    readonly MutationRecord: false
    readonly name: false
    readonly NamedNodeMap: false
    readonly NavigateEvent: false
    readonly navigation: false
    readonly Navigation: false
    readonly NavigationActivation: false
    readonly NavigationCurrentEntryChangeEvent: false
    readonly NavigationDestination: false
    readonly NavigationHistoryEntry: false
    readonly NavigationPreloadManager: false
    readonly NavigationTransition: false
    readonly NavigatorLogin: false
    readonly NavigatorManagedData: false
    readonly NavigatorUAData: false
    readonly NetworkInformation: false
    readonly Node: false
    readonly NodeFilter: false
    readonly NodeIterator: false
    readonly NodeList: false
    readonly Notification: false
    readonly NotifyPaintEvent: false
    readonly NotRestoredReasonDetails: false
    readonly NotRestoredReasons: false
    readonly Observable: false
    readonly OfflineAudioCompletionEvent: false
    readonly OfflineAudioContext: false
    readonly offscreenBuffering: false
    readonly OffscreenCanvas: false
    readonly OffscreenCanvasRenderingContext2D: false
    readonly onabort: true
    readonly onafterprint: true
    readonly onanimationcancel: true
    readonly onanimationend: true
    readonly onanimationiteration: true
    readonly onanimationstart: true
    readonly onappinstalled: true
    readonly onauxclick: true
    readonly onbeforeinput: true
    readonly onbeforeinstallprompt: true
    readonly onbeforematch: true
    readonly onbeforeprint: true
    readonly onbeforetoggle: true
    readonly onbeforeunload: true
    readonly onbeforexrselect: true
    readonly onblur: true
    readonly oncancel: true
    readonly oncanplay: true
    readonly oncanplaythrough: true
    readonly onchange: true
    readonly onclick: true
    readonly onclose: true
    readonly oncommand: true
    readonly oncontentvisibilityautostatechange: true
    readonly oncontextlost: true
    readonly oncontextmenu: true
    readonly oncontextrestored: true
    readonly oncopy: true
    readonly oncuechange: true
    readonly oncut: true
    readonly ondblclick: true
    readonly ondevicemotion: true
    readonly ondeviceorientation: true
    readonly ondeviceorientationabsolute: true
    readonly ondrag: true
    readonly ondragend: true
    readonly ondragenter: true
    readonly ondragleave: true
    readonly ondragover: true
    readonly ondragstart: true
    readonly ondrop: true
    readonly ondurationchange: true
    readonly onemptied: true
    readonly onended: true
    readonly onerror: true
    readonly onfocus: true
    readonly onformdata: true
    readonly ongamepadconnected: true
    readonly ongamepaddisconnected: true
    readonly ongotpointercapture: true
    readonly onhashchange: true
    readonly oninput: true
    readonly oninvalid: true
    readonly onkeydown: true
    readonly onkeypress: true
    readonly onkeyup: true
    readonly onlanguagechange: true
    readonly onload: true
    readonly onloadeddata: true
    readonly onloadedmetadata: true
    readonly onloadstart: true
    readonly onlostpointercapture: true
    readonly onmessage: true
    readonly onmessageerror: true
    readonly onmousedown: true
    readonly onmouseenter: true
    readonly onmouseleave: true
    readonly onmousemove: true
    readonly onmouseout: true
    readonly onmouseover: true
    readonly onmouseup: true
    readonly onmousewheel: true
    readonly onoffline: true
    readonly ononline: true
    readonly onpagehide: true
    readonly onpagereveal: true
    readonly onpageshow: true
    readonly onpageswap: true
    readonly onpaste: true
    readonly onpause: true
    readonly onplay: true
    readonly onplaying: true
    readonly onpointercancel: true
    readonly onpointerdown: true
    readonly onpointerenter: true
    readonly onpointerleave: true
    readonly onpointermove: true
    readonly onpointerout: true
    readonly onpointerover: true
    readonly onpointerrawupdate: true
    readonly onpointerup: true
    readonly onpopstate: true
    readonly onprogress: true
    readonly onratechange: true
    readonly onrejectionhandled: true
    readonly onreset: true
    readonly onresize: true
    readonly onscroll: true
    readonly onscrollend: true
    readonly onscrollsnapchange: true
    readonly onscrollsnapchanging: true
    readonly onsearch: true
    readonly onsecuritypolicyviolation: true
    readonly onseeked: true
    readonly onseeking: true
    readonly onselect: true
    readonly onselectionchange: true
    readonly onselectstart: true
    readonly onslotchange: true
    readonly onstalled: true
    readonly onstorage: true
    readonly onsubmit: true
    readonly onsuspend: true
    readonly ontimeupdate: true
    readonly ontoggle: true
    readonly ontransitioncancel: true
    readonly ontransitionend: true
    readonly ontransitionrun: true
    readonly ontransitionstart: true
    readonly onunhandledrejection: true
    readonly onunload: true
    readonly onvolumechange: true
    readonly onwaiting: true
    readonly onwheel: true
    readonly open: false
    readonly opener: false
    readonly Option: false
    readonly OrientationSensor: false
    readonly origin: false
    readonly originAgentCluster: false
    readonly OscillatorNode: false
    readonly OTPCredential: false
    readonly outerHeight: false
    readonly outerWidth: false
    readonly OverconstrainedError: false
    readonly PageRevealEvent: false
    readonly PageSwapEvent: false
    readonly PageTransitionEvent: false
    readonly pageXOffset: false
    readonly pageYOffset: false
    readonly PannerNode: false
    readonly parent: false
    readonly PasswordCredential: false
    readonly Path2D: false
    readonly PaymentAddress: false
    readonly PaymentManager: false
    readonly PaymentMethodChangeEvent: false
    readonly PaymentRequest: false
    readonly PaymentRequestUpdateEvent: false
    readonly PaymentResponse: false
    readonly PerformanceElementTiming: false
    readonly PerformanceEventTiming: false
    readonly PerformanceLongAnimationFrameTiming: false
    readonly PerformanceLongTaskTiming: false
    readonly PerformanceNavigation: false
    readonly PerformanceNavigationTiming: false
    readonly PerformancePaintTiming: false
    readonly PerformanceScriptTiming: false
    readonly PerformanceServerTiming: false
    readonly PerformanceTiming: false
    readonly PeriodicSyncManager: false
    readonly PeriodicWave: false
    readonly Permissions: false
    readonly PermissionStatus: false
    readonly PERSISTENT: false
    readonly personalbar: false
    readonly PictureInPictureEvent: false
    readonly PictureInPictureWindow: false
    readonly Plugin: false
    readonly PluginArray: false
    readonly PointerEvent: false
    readonly PopStateEvent: false
    readonly postMessage: false
    readonly Presentation: false
    readonly PresentationAvailability: false
    readonly PresentationConnection: false
    readonly PresentationConnectionAvailableEvent: false
    readonly PresentationConnectionCloseEvent: false
    readonly PresentationConnectionList: false
    readonly PresentationReceiver: false
    readonly PresentationRequest: false
    readonly PressureObserver: false
    readonly PressureRecord: false
    readonly print: false
    readonly ProcessingInstruction: false
    readonly Profiler: false
    readonly ProgressEvent: false
    readonly PromiseRejectionEvent: false
    readonly prompt: false
    readonly ProtectedAudience: false
    readonly PublicKeyCredential: false
    readonly PushManager: false
    readonly PushSubscription: false
    readonly PushSubscriptionOptions: false
    readonly queryLocalFonts: false
    readonly RadioNodeList: false
    readonly Range: false
    readonly registerProcessor: false
    readonly RelativeOrientationSensor: false
    readonly RemotePlayback: false
    readonly removeEventListener: false
    readonly ReportBody: false
    readonly reportError: false
    readonly ReportingObserver: false
    readonly requestAnimationFrame: false
    readonly requestIdleCallback: false
    readonly resizeBy: false
    readonly ResizeObserver: false
    readonly ResizeObserverEntry: false
    readonly ResizeObserverSize: false
    readonly resizeTo: false
    readonly RestrictionTarget: false
    readonly RTCCertificate: false
    readonly RTCDataChannel: false
    readonly RTCDataChannelEvent: false
    readonly RTCDtlsTransport: false
    readonly RTCDTMFSender: false
    readonly RTCDTMFToneChangeEvent: false
    readonly RTCEncodedAudioFrame: false
    readonly RTCEncodedVideoFrame: false
    readonly RTCError: false
    readonly RTCErrorEvent: false
    readonly RTCIceCandidate: false
    readonly RTCIceTransport: false
    readonly RTCPeerConnection: false
    readonly RTCPeerConnectionIceErrorEvent: false
    readonly RTCPeerConnectionIceEvent: false
    readonly RTCRtpReceiver: false
    readonly RTCRtpScriptTransform: false
    readonly RTCRtpSender: false
    readonly RTCRtpTransceiver: false
    readonly RTCSctpTransport: false
    readonly RTCSessionDescription: false
    readonly RTCStatsReport: false
    readonly RTCTrackEvent: false
    readonly sampleRate: false
    readonly scheduler: false
    readonly Scheduler: false
    readonly Scheduling: false
    readonly screen: false
    readonly Screen: false
    readonly ScreenDetailed: false
    readonly ScreenDetails: false
    readonly screenLeft: false
    readonly ScreenOrientation: false
    readonly screenTop: false
    readonly screenX: false
    readonly screenY: false
    readonly ScriptProcessorNode: false
    readonly scroll: false
    readonly scrollbars: false
    readonly scrollBy: false
    readonly ScrollTimeline: false
    readonly scrollTo: false
    readonly scrollX: false
    readonly scrollY: false
    readonly SecurityPolicyViolationEvent: false
    readonly Selection: false
    readonly self: false
    readonly Sensor: false
    readonly SensorErrorEvent: false
    readonly Serial: false
    readonly SerialPort: false
    readonly ServiceWorker: false
    readonly ServiceWorkerContainer: false
    readonly ServiceWorkerRegistration: false
    readonly sessionStorage: false
    readonly ShadowRoot: false
    readonly sharedStorage: false
    readonly SharedStorage: false
    readonly SharedStorageAppendMethod: false
    readonly SharedStorageClearMethod: false
    readonly SharedStorageDeleteMethod: false
    readonly SharedStorageModifierMethod: false
    readonly SharedStorageSetMethod: false
    readonly SharedStorageWorklet: false
    readonly SharedWorker: false
    readonly showDirectoryPicker: false
    readonly showOpenFilePicker: false
    readonly showSaveFilePicker: false
    readonly SnapEvent: false
    readonly SourceBuffer: false
    readonly SourceBufferList: false
    readonly speechSynthesis: false
    readonly SpeechSynthesis: false
    readonly SpeechSynthesisErrorEvent: false
    readonly SpeechSynthesisEvent: false
    readonly SpeechSynthesisUtterance: false
    readonly SpeechSynthesisVoice: false
    readonly StaticRange: false
    readonly status: false
    readonly statusbar: false
    readonly StereoPannerNode: false
    readonly stop: false
    readonly Storage: false
    readonly StorageBucket: false
    readonly StorageBucketManager: false
    readonly StorageEvent: false
    readonly StorageManager: false
    readonly styleMedia: false
    readonly StylePropertyMap: false
    readonly StylePropertyMapReadOnly: false
    readonly StyleSheet: false
    readonly StyleSheetList: false
    readonly SubmitEvent: false
    readonly Subscriber: false
    readonly SVGAElement: false
    readonly SVGAngle: false
    readonly SVGAnimatedAngle: false
    readonly SVGAnimatedBoolean: false
    readonly SVGAnimatedEnumeration: false
    readonly SVGAnimatedInteger: false
    readonly SVGAnimatedLength: false
    readonly SVGAnimatedLengthList: false
    readonly SVGAnimatedNumber: false
    readonly SVGAnimatedNumberList: false
    readonly SVGAnimatedPreserveAspectRatio: false
    readonly SVGAnimatedRect: false
    readonly SVGAnimatedString: false
    readonly SVGAnimatedTransformList: false
    readonly SVGAnimateElement: false
    readonly SVGAnimateMotionElement: false
    readonly SVGAnimateTransformElement: false
    readonly SVGAnimationElement: false
    readonly SVGCircleElement: false
    readonly SVGClipPathElement: false
    readonly SVGComponentTransferFunctionElement: false
    readonly SVGDefsElement: false
    readonly SVGDescElement: false
    readonly SVGElement: false
    readonly SVGEllipseElement: false
    readonly SVGFEBlendElement: false
    readonly SVGFEColorMatrixElement: false
    readonly SVGFEComponentTransferElement: false
    readonly SVGFECompositeElement: false
    readonly SVGFEConvolveMatrixElement: false
    readonly SVGFEDiffuseLightingElement: false
    readonly SVGFEDisplacementMapElement: false
    readonly SVGFEDistantLightElement: false
    readonly SVGFEDropShadowElement: false
    readonly SVGFEFloodElement: false
    readonly SVGFEFuncAElement: false
    readonly SVGFEFuncBElement: false
    readonly SVGFEFuncGElement: false
    readonly SVGFEFuncRElement: false
    readonly SVGFEGaussianBlurElement: false
    readonly SVGFEImageElement: false
    readonly SVGFEMergeElement: false
    readonly SVGFEMergeNodeElement: false
    readonly SVGFEMorphologyElement: false
    readonly SVGFEOffsetElement: false
    readonly SVGFEPointLightElement: false
    readonly SVGFESpecularLightingElement: false
    readonly SVGFESpotLightElement: false
    readonly SVGFETileElement: false
    readonly SVGFETurbulenceElement: false
    readonly SVGFilterElement: false
    readonly SVGForeignObjectElement: false
    readonly SVGGElement: false
    readonly SVGGeometryElement: false
    readonly SVGGradientElement: false
    readonly SVGGraphicsElement: false
    readonly SVGImageElement: false
    readonly SVGLength: false
    readonly SVGLengthList: false
    readonly SVGLinearGradientElement: false
    readonly SVGLineElement: false
    readonly SVGMarkerElement: false
    readonly SVGMaskElement: false
    readonly SVGMatrix: false
    readonly SVGMetadataElement: false
    readonly SVGMPathElement: false
    readonly SVGNumber: false
    readonly SVGNumberList: false
    readonly SVGPathElement: false
    readonly SVGPatternElement: false
    readonly SVGPoint: false
    readonly SVGPointList: false
    readonly SVGPolygonElement: false
    readonly SVGPolylineElement: false
    readonly SVGPreserveAspectRatio: false
    readonly SVGRadialGradientElement: false
    readonly SVGRect: false
    readonly SVGRectElement: false
    readonly SVGScriptElement: false
    readonly SVGSetElement: false
    readonly SVGStopElement: false
    readonly SVGStringList: false
    readonly SVGStyleElement: false
    readonly SVGSVGElement: false
    readonly SVGSwitchElement: false
    readonly SVGSymbolElement: false
    readonly SVGTextContentElement: false
    readonly SVGTextElement: false
    readonly SVGTextPathElement: false
    readonly SVGTextPositioningElement: false
    readonly SVGTitleElement: false
    readonly SVGTransform: false
    readonly SVGTransformList: false
    readonly SVGTSpanElement: false
    readonly SVGUnitTypes: false
    readonly SVGUseElement: false
    readonly SVGViewElement: false
    readonly SyncManager: false
    readonly TaskAttributionTiming: false
    readonly TaskController: false
    readonly TaskPriorityChangeEvent: false
    readonly TaskSignal: false
    readonly TEMPORARY: false
    readonly Text: false
    readonly TextEvent: false
    readonly TextFormat: false
    readonly TextFormatUpdateEvent: false
    readonly TextMetrics: false
    readonly TextTrack: false
    readonly TextTrackCue: false
    readonly TextTrackCueList: false
    readonly TextTrackList: false
    readonly TextUpdateEvent: false
    readonly TimeEvent: false
    readonly TimeRanges: false
    readonly ToggleEvent: false
    readonly toolbar: false
    readonly top: false
    readonly Touch: false
    readonly TouchEvent: false
    readonly TouchList: false
    readonly TrackEvent: false
    readonly TransitionEvent: false
    readonly TreeWalker: false
    readonly TrustedHTML: false
    readonly TrustedScript: false
    readonly TrustedScriptURL: false
    readonly TrustedTypePolicy: false
    readonly TrustedTypePolicyFactory: false
    readonly trustedTypes: false
    readonly UIEvent: false
    readonly USB: false
    readonly USBAlternateInterface: false
    readonly USBConfiguration: false
    readonly USBConnectionEvent: false
    readonly USBDevice: false
    readonly USBEndpoint: false
    readonly USBInterface: false
    readonly USBInTransferResult: false
    readonly USBIsochronousInTransferPacket: false
    readonly USBIsochronousInTransferResult: false
    readonly USBIsochronousOutTransferPacket: false
    readonly USBIsochronousOutTransferResult: false
    readonly USBOutTransferResult: false
    readonly UserActivation: false
    readonly ValidityState: false
    readonly VideoColorSpace: false
    readonly VideoDecoder: false
    readonly VideoEncoder: false
    readonly VideoFrame: false
    readonly VideoPlaybackQuality: false
    readonly ViewTimeline: false
    readonly ViewTransition: false
    readonly ViewTransitionTypeSet: false
    readonly VirtualKeyboard: false
    readonly VirtualKeyboardGeometryChangeEvent: false
    readonly VisibilityStateEntry: false
    readonly visualViewport: false
    readonly VisualViewport: false
    readonly VTTCue: false
    readonly VTTRegion: false
    readonly WakeLock: false
    readonly WakeLockSentinel: false
    readonly WaveShaperNode: false
    readonly WebGL2RenderingContext: false
    readonly WebGLActiveInfo: false
    readonly WebGLBuffer: false
    readonly WebGLContextEvent: false
    readonly WebGLFramebuffer: false
    readonly WebGLObject: false
    readonly WebGLProgram: false
    readonly WebGLQuery: false
    readonly WebGLRenderbuffer: false
    readonly WebGLRenderingContext: false
    readonly WebGLSampler: false
    readonly WebGLShader: false
    readonly WebGLShaderPrecisionFormat: false
    readonly WebGLSync: false
    readonly WebGLTexture: false
    readonly WebGLTransformFeedback: false
    readonly WebGLUniformLocation: false
    readonly WebGLVertexArrayObject: false
    readonly WebSocketError: false
    readonly WebSocketStream: false
    readonly WebTransport: false
    readonly WebTransportBidirectionalStream: false
    readonly WebTransportDatagramDuplexStream: false
    readonly WebTransportError: false
    readonly WebTransportReceiveStream: false
    readonly WebTransportSendStream: false
    readonly WGSLLanguageFeatures: false
    readonly WheelEvent: false
    readonly when: false
    readonly window: false
    readonly Window: false
    readonly WindowControlsOverlay: false
    readonly WindowControlsOverlayGeometryChangeEvent: false
    readonly Worker: false
    readonly Worklet: false
    readonly WorkletGlobalScope: false
    readonly XMLDocument: false
    readonly XMLHttpRequest: false
    readonly XMLHttpRequestEventTarget: false
    readonly XMLHttpRequestUpload: false
    readonly XMLSerializer: false
    readonly XPathEvaluator: false
    readonly XPathExpression: false
    readonly XPathResult: false
    readonly XRAnchor: false
    readonly XRAnchorSet: false
    readonly XRBoundedReferenceSpace: false
    readonly XRCamera: false
    readonly XRCPUDepthInformation: false
    readonly XRDepthInformation: false
    readonly XRDOMOverlayState: false
    readonly XRFrame: false
    readonly XRHand: false
    readonly XRHitTestResult: false
    readonly XRHitTestSource: false
    readonly XRInputSource: false
    readonly XRInputSourceArray: false
    readonly XRInputSourceEvent: false
    readonly XRInputSourcesChangeEvent: false
    readonly XRJointPose: false
    readonly XRJointSpace: false
    readonly XRLayer: false
    readonly XRLightEstimate: false
    readonly XRLightProbe: false
    readonly XRPose: false
    readonly XRRay: false
    readonly XRReferenceSpace: false
    readonly XRReferenceSpaceEvent: false
    readonly XRRenderState: false
    readonly XRRigidTransform: false
    readonly XRSession: false
    readonly XRSessionEvent: false
    readonly XRSpace: false
    readonly XRSystem: false
    readonly XRTransientInputHitTestResult: false
    readonly XRTransientInputHitTestSource: false
    readonly XRView: false
    readonly XRViewerPose: false
    readonly XRViewport: false
    readonly XRWebGLBinding: false
    readonly XRWebGLDepthInformation: false
    readonly XRWebGLLayer: false
    readonly XSLTProcessor: false
  } & {
    readonly suite: 'writable'
    readonly test: 'writable'
    readonly chai: 'writable'
    readonly describe: 'writable'
    readonly it: 'writable'
    readonly expectTypeOf: 'writable'
    readonly assertType: 'writable'
    readonly expect: 'writable'
    readonly assert: 'writable'
    readonly vitest: 'writable'
    readonly vi: 'writable'
    readonly beforeAll: 'writable'
    readonly afterAll: 'writable'
    readonly beforeEach: 'writable'
    readonly afterEach: 'writable'
    readonly onTestFailed: 'writable'
    readonly onTestFinished: 'writable'
  }
