import type { ActionCreatorWithPayload, PayloadAction } from './createAction'
import type { CaseReducer } from './createReducer'

const prefixAutoActionCreator = 'set'

/**
 *  /**
 * Generates action creators for each property in a state object.
 *
 * This utility type creates a mapped type where each property in the state
 * becomes an action creator with the property name capitalized and prefixed with 'set'.
 *
 * @template State - The shape of the slice state. Must be an object type.
 * @template Name - The string literal type used as the action type prefix.
 *
 * @example
 * ```typescript
 * // Given prefixAutoActionCreator = 'set'
 * type UserState = {
 *   name: string;
 *   age: number;
 *   active: boolean;
 * };
 *
 * type UserAutoActionCreators = AutoActionCreators<UserState, "user">;
 *
 * // Results in:
 * // {
 * //   setName: ActionCreatorWithPayload<string, "user">;
 * //   setAge: ActionCreatorWithPayload<number, "user">;
 * //   setActive: ActionCreatorWithPayload<boolean, "user">;
 * // }
 *
 * // Usage in component/dispatcher:
 * dispatch(actions.setName("John"));
 * dispatch(actions.setAge(30));
 * ```
 *
 * @remarks
 * The action names are generated by taking each property key, capitalizing it,
 * and prefixing it with 'set'. This follows a common convention similar to React's
 * `setState` pattern and provides intuitive action names like `setName`, `setAge`, etc.
 *
 * @public
 */
export type AutoActionCreators<State extends any, Name extends string> = {
  [stateName in keyof State as `${typeof prefixAutoActionCreator}${Capitalize<string & stateName>}`]: ActionCreatorWithPayload<
    State[stateName],
    Name
  >
}

/**
 * Generates case reducers for each property in a state object.
 *
 * This utility type creates a mapped type where each property in the state
 * becomes a case reducer function that updates that specific property when
 * a corresponding 'set' action is dispatched.
 *
 * @template State - The shape of the slice state. Must be an object type.
 *
 * @example
 * ```typescript
 * type UserState = {
 *   name: string;
 *   age: number;
 *   active: boolean;
 * };
 *
 * type UserAutoReducers = AutoReducers<UserState>;
 *
 * // Results in:
 * // {
 * //   setName: CaseReducer<UserState, PayloadAction<string>>;
 * //   setAge: CaseReducer<UserState, PayloadAction<number>>;
 * //   setActive: CaseReducer<UserState, PayloadAction<boolean>>;
 * // }
 *
 * // Usage in createSlice:
 * const userSlice = createSlice({
 *   name: 'user',
 *   initialState: { name: '', age: 0, active: false },
 *   reducers: {
 *     ...autoReducers, // Spread auto-generated reducers
 *     // Add custom reducers as needed
 *   }
 * });
 * ```
 *
 * @remarks
 * Each generated case reducer follows the pattern:
 * - Function name: `set` + CapitalizedPropertyName (e.g., `setName` for `name` property)
 * - Parameters: `(state: State, action: PayloadAction<PropertyType>)`
 * - Implementation: Updates the specific property in the state
 *
 * @public
 */
export type AutoReducers<State> = {
  [stateName in keyof State as `${typeof prefixAutoActionCreator}${Capitalize<string & stateName>}`]: CaseReducer<
    State,
    PayloadAction<State[stateName]>
  >
}

type MergeDefaults<T, D> = T & Omit<D, keyof T>

/**
 * /**
 * Merges manually defined case reducer actions with automatically generated 'set' actions.
 * 
 * This type combines two sets of action creators:
 * 1. `CaseReducerActions` - Action creators defined explicitly in a slice's reducers
 * 2. `AutoActionCreator` - Action creators automatically generated from the state shape (prefixed with 'set')
 * 
 * @template CaseReducerActions - The action creators from explicit reducers
 * @template AutoActionCreator - The auto-generated 'set' action creators from `AutoActionCreators`
 * 
 * @example
 * ```typescript
 * const userSlice = createSlice({
 *   name: 'user',
 *   initialState: { name: '', age: 0, active: false },
 *   reducers: {
 *     // Manually defined action
 *     updateProfile: (state, action: PayloadAction<Partial<UserState>>) => {
 *       Object.assign(state, action.payload);
 *     }
 *   }
 * });
 * 
 * type ManualActionCreators = typeof userSlice.actions;
 * type AutoGeneratedActionCreators = AutoActionCreators<UserState, "user">;
 * 
 * // Combined actions include:
 * // - 'updateProfile' (manual)
 * // - 'setName', 'setAge', 'setActive' (auto-generated)
 * type AllActions = MergeWithAutoActions<ManualActionCreators, AutoGeneratedActionCreators>;
 * 
 * // Usage:
 * dispatch(actions.updateProfile({ name: "John", age: 30 }));
 * dispatch(actions.setActive(true)); // Auto-generated action
 * ```

 * @private
 */
export type MergeWithAutoActions<
  CaseReducerActions,
  AutoActionCreator extends AutoActionCreators<any, string>,
> = MergeDefaults<CaseReducerActions, AutoActionCreator>

type UnknownRecord = Record<string, unknown>

const capitalize = (value: string) =>
  value.toUpperCase().slice(0, 1) + value.slice(1)

/**
 * Generates reducers for each property in a state object.
 *
 * @template State - The type of the slice state
 * @template Name - The string literal type used as the action type prefix
 * @param {State | (() => State)} initialState - The initial state of the slice
 * @returns {AutoActionCreators<State, Name>} An object containing reducers for each state property
 * @example
 * ```typescript
 * const initialState = { count: 0, name: '' };
 *
 * const autoReducers = generateAutoReducers(initialState);
 *
 * // Returns: {
 * //   setCount: (state, { payload }) => { state.count = payload; },
 * //   setName: (state, { payload }) => { state.name = payload; }
 * // }
 * ```
 * @remarks
 * This function is used internally to automatically generate reducer functions
 * for each property in the state. Each generated reducer updates a single
 * state property when the corresponding 'set' action is dispatched.
 *
 * The function handles both object initial states and initial state factories.
 *
 *  @private
 */
export const createAutoReducers = <State>(
  initialState: State | (() => State),
) => {
  const state =
    typeof initialState === 'function'
      ? (initialState as Function)()
      : initialState

  const stateFieldNames = Object.keys(state)

  return stateFieldNames.reduce<Partial<UnknownRecord>>((acc, fieldName) => {
    const capitalizeFieldName = `${prefixAutoActionCreator}${capitalize(fieldName)}`

    acc[capitalizeFieldName] = (
      state: State,
      { payload }: PayloadAction<State[keyof State]>,
    ) => {
      ;(state as UnknownRecord)[fieldName] = payload
    }

    return acc
  }, {}) as AutoReducers<State>
}
